### ISSUE TITLE
Stop flight at end of island area

### ISSUE THREAD

**Issue by garet90** [garet90/simple-skyblock#26]
Could you please add a feature that lets players get creative flight while on their island only (and if they leave their island area, they lose flight but don’t take fall damage during the fall to the ground)?

I’d love if there were a permission for this (e.g., simpleskyblock.fly) so that it could be unlocked with a rank. This would be perfect for my server, which is in development.

Is this something you could implement? If so, that’d be wonderful! :)

**Comment by garet90** [comment]
Added in next commit

**Comment by Nevrai** [comment]
Thanks!
