### ISSUE TITLE
Cost for resets

### ISSUE THREAD

**Issue by garet90** [garet90/simple-skyblock#28]
I have a suggestion for a feature that’d be super useful if implemented:
Could you please add a feature that, if enabled, causes island resets to cost in-game money? It’d also be sweet if one could customize what the price for each reset costs.

For instance, the relevant part of the config could look something like this:

PAY_FOR_RESET: true
RESET1: 10
RESET2: 30
RESET3:50
RESET4:105
RESET5:130
RESET6:160
RESET7: 200
RESET8: 300
RESET9: 500
RESET10: 1000

…and so on. In this example, a player’s first reset would cost $10, a player’s second reset would cost $30, their third $50, their fourth $105, and so on. And once they reach 10 resets, it’d cost $1,000 each time until they run out of resets.

**Comment by garet90** [comment]
Added in next update

**Comment by Nevrai** [comment]
Thanks!
