### ISSUE TITLE
[Suggestion] Use schematic files for islands

### ISSUE THREAD

**Issue by Nevrai** [garet90/simple-skyblock#29]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you’d like**
I want Simple Skyblock to use schematic files instead of confusing YML files. I know that I already suggested this [in the SpigotMC discussion thread](https://www.spigotmc.org/threads/simple-skyblock-1-8-x-1-15-x.400459/page-2#post-3662574) nearly two weeks ago, but I’m creating this issue so that you don’t forget about it, if you still wish to implement it.

**Describe alternatives you’ve considered**
I have considered modifying the complicated YML files, but I can’t, because I don’t know how to. It’d be much simpler and convenient to just be able to create a schematic using [WorldEdit](https://dev.bukkit.org/projects/worldedit) and import it as an island template in Simple Skyblock.

I don’t believe that WorldEdit needs to be a hard dependency as Simple Skyblock can just come with a default schematic file in case the user doesn’t want to modify it. If it does, though, perhaps it could use YML files by default, just like it does now, but have a config option that, when enabled, makes it use schematic files instead.

There are other skyblock plugins that manage to do this, such as [Iridium Skyblock](https://www.spigotmc.org/resources/iridium-skyblock-1-8-1-15.62480/). If you could implement this feature into Simple Skyblock, that’d be much appreciated! 💙

**Additional context**
N/A

**Comment by garet90** [comment]
Added in recent commit. Will be in next update
