### ISSUE TITLE
Can't trade money

### ISSUE THREAD

**Issue by tmoyer** [garet90/simple-skyblock#3]
I have the latest version of Simple Skyblock (1.2.2) installed and all is working great, except that you can't trade money. You can trade items, but not money. I'm using LuckPerms and enabled permissions for trading. I don't see anything in the config.yml file that would indicate any configuration I need to do. I'd really love to get this working.

**Comment by garet90** [comment]
Trading seems to be working on my test server. Could you post your config file? I'll check it out, and see if I can fix the problem, it might be some other setting that accidentally interferes or something in the code. Thanks!
