### ISSUE TITLE
[Suggestion] Per-world void instant death

### ISSUE THREAD

**Issue by Nevrai** [garet90/simple-skyblock#30]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you’d like**
A config option to enable void instant death per world.

**Describe alternatives you’ve considered**
N/A

**Additional context**
I only want the void instant death feature to be enabled in skyblock worlds. My server also has survival worlds, so I don’t want it to be enabled in them.

**Comment by garet90** [comment]
Added in next update
