### ISSUE TITLE
Teleporting with scoreboards such as Faction's scoreboard removes it

### ISSUE THREAD

**Issue by Jadiction** [garet90/simple-skyblock#31]
**Describe the bug**
This is a weird bug to describe, but when going into a world with a scoreboard, such as a factions world using a factions scoreboard and teleporting to another world (for example going to the nether, the end, a multiverse world, etc...) it essentially "disables" the scoreboard.

**To Reproduce**
1. Use [Factions with scoreboards on](https://www.spigotmc.org/resources/factionsuuid.1035/).
2. Go to nether world or end
3. Go back to overworld and the scoreboard is gone

**Expected behavior**
Scoreboards to not be affected.

**Server (please complete the following information):**
 - OS: Linux
 - Type: Paper
 - Version: 1.15.2
 - SS-Version: 1.3.7

**Console**
No console errors occurred.

**Comment by garet90** [comment]
Disabling DISABLE_COLLISIONS should fix this, as I'm pretty sure the collision disabling uses scoreboard options to do this. I'll leave this open and look into a way you can have disable collisions on and not clear scoreboards

**Comment by garet90** [comment]
Not fixing this bug for the foreseeable future. Someone else may work to implement this, by coming up with a way to disable collisions without using the scoreboard. LivingEntity#setCollidable has been notorious for not working. You may have to go without the collisions disabled for a time. I am worried that interfering with the scoreboard could cause more problems than it's worth.
