### ISSUE TITLE
Make it compatible with Skript

### ISSUE THREAD

**Issue by Zizaz** [garet90/simple-skyblock#32]
**Is your feature request related to a problem? Please describe.**
As I am created a skyblock server i use Skript for different things, and i encounter a problem with
how you made your cobblestone generator. as i want to generate chest with random content it is 
impossible with the way you made it : you're settings the block ( not forming ), i can't detect it 
and if i could, the second part of your algorithm is based on what it was set so points aren't count.

**Describe the solution you'd like**
make it that you form a block and not setting it.
for the points part is different aas Skript is replacing the block. It can't be count as there is difference between what was formed and what it is actually generate.

OR

handle the possibility to create chest with random content (not so random as it is listed in the .yml file).

**Describe alternatives you've considered**
for the moment there is none, or generate a new jar from your source and nullify the lava part of your plugin ( which i don't want to because you did an amazing job ).

**Additional context**
Love your plugin, incredible useful ! ❤
if you need any help i'm ok :)

**Comment by garet90** [comment]
Hopefully this works: [http://files.garet.holiday/skyblock-1.3.8-test.jar](http://files.garet.holiday/skyblock-1.3.8-test.jar)
If not, just comment, I'll leave this open for now

**Comment by garet90** [comment]
As a part of tradition, this will be closed as it has not received feedback in over a week, but it may be reopened.

**Comment by Zizaz** [comment]
Thanks for your response, so i did some experience with your plugin and found something quite strange
there is a strange behavior between flowing water and flowing lava, especially the order of which one meet the other.

i explain :

simple cobblestone generator : water placed next to a hole that way the water will automatically flow into the hole, and lava flowing into the running water : triggers your ore generator,

now do it the other way round : water flowing into running lava : it ll triggers skript 

i don't know if it's a bug from your plugin, skript plugin or minecraft himself.

PS : the simple skript in attach files 
[test.txt](https://github.com/garet90/simple-skyblock/files/4588788/test.txt)

**Comment by garet90** [comment]
Ah, I see, I think it is mostly my bad, I should listen to onBlockForm event instead of onFromToEvent, and I think that might be part of the problem. I will most likely change this in the next update
