### ISSUE TITLE
Issues with island generation

### ISSUE THREAD

**Issue by wagpool** [garet90/simple-skyblock#45]
After updating to the newer version, any new islands that are created will spawn in the SAME world, but there is now land there. Therefore the islands will spawn in the middle of a hill, for example, or in the ocean.

**Comment by garet90** [comment]
Can you attach your bukkit.yml and your plugins/SimpleSkyblock/config.yml file?

**Comment by wagpool** [comment]
[bukkityml.txt](https://github.com/garet90/simple-skyblock/files/4677196/bukkityml.txt)
[SBconfigyml.txt](https://github.com/garet90/simple-skyblock/files/4677197/SBconfigyml.txt)
Have attached as TXT files if that's okay

**Comment by garet90** [comment]
Try adding

worlds:
  SkyBWorld:
    generator: SimpleSkyblock
  SkyBWorld_nether
    generator: SimpleSkyblock

To your bukkit.yml
That usually fixes any world generation problems by explicitly handing world generation to SimpleSkyblock.

If you need anything else, feel free re open this issue or contact me some other way.

**Comment by wagpool** [comment]
Hiya,
I added that to the end of my bukkit.yml and it changed all of it to just ‘generator: SimpleSkyblock’ and it didn’t make any difference to island generation. What else is there that I can do?

Thanks,
Abbie

**Comment by wagpool** [comment]
Hiya,
Apologies for the second email, I was just how I create the nether islands?

**Comment by garet90** [comment]
Try the latest dev release: https://files.garet.holiday/SimpleSkyblock-1.4.0-pre6.jar

For nether island structures you add _nether to the schematic, so default.nbt is the default structure and default_nether.nbt is the nether counterpart.

**Comment by wagpool** [comment]
Hiya,
I tried the new release but now islands generate above flat sandstone ground, nothing else.
Thanks,
Abbie

**Comment by wagpool** [comment]
Hiya,
Apologies for the second email! The skyblock file had the generator in a world called ‘world’, which was the sandstone world. I have changed it back to what it was originally called and the issue still persists, it’s back in a normal world now, and produces islands in the middle of the ground.
Thanks,
Abbie

**Comment by wagpool** [comment]
Hiya,
I’ve used your skyblock plugin for a while and it’s gone back to using a full world, I’ve tried changing which world it uses, I’ve added the
World:
Worldname:
Generator: simpleskyblock
To the bukkit.yml yet it still just spawns in the middle of land, do you have an idea how to fix this please? 
Thanks,
Abbie
